# Generated by Codex on 2026-05-13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTVChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('stream_url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator()])),
                ('source_id', models.CharField(max_length=300, unique=True)),
                ('source_name', models.CharField(default='iptv-org', max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('tvg_id', models.CharField(blank=True, max_length=255)),
                ('logo', models.URLField(blank=True, max_length=1000)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=12)),
                ('language', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='iptvchannel',
            index=models.Index(fields=['category', 'country_code'], name='sports_iptv_categor_6bffa9_idx'),
        ),
        migrations.AddIndex(
            model_name='iptvchannel',
            index=models.Index(fields=['is_active', 'is_featured'], name='sports_iptv_is_acti_48a3c3_idx'),
        ),
    ]
