# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_iptvchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptvchannel',
            name='slug',
            field=models.SlugField(max_length=280, unique=True),
        ),
    ]
