# Generated by Django 5.0 on 2026-05-14 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_iptvchannel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreative',
            name='click_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='ad_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('video', 'Video'), ('popup', 'Popup'), ('sidebar', 'Sidebar'), ('interstitial', 'Interstitial')], default='banner', max_length=20),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='rotation_interval',
            field=models.IntegerField(default=30, help_text='Seconds between ad rotation'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('preview', 'Match Preview'), ('review', 'Match Review'), ('highlight', 'Highlights'), ('transfer', 'Transfer News'), ('analysis', 'Analysis'), ('interview', 'Interview')], default='news', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sport'),
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iptvchannel',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iptvchannel',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='player_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='team_side',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='iptvchannel',
            name='stream_url',
            field=models.URLField(max_length=2000, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='scoreevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('wicket', 'Wicket'), ('boundary', 'Boundary'), ('six', 'Six'), ('substitution', 'Substitution'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('period_start', 'Period Start'), ('period_end', 'Period End'), ('penalty', 'Penalty'), ('injury', 'Injury'), ('var_check', 'VAR Check'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='streamsource',
            name='provider',
            field=models.CharField(choices=[('hls', 'HLS/M3U8'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('akamai', 'Akamai CDN'), ('custom', 'Custom/ISP'), ('iframe', 'iFrame Embed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='streamsource',
            name='url',
            field=models.URLField(max_length=2000, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.CreateModel(
            name='LiveCommentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('original_text', models.TextField(blank=True)),
                ('rewritten_text', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('crawled', 'Crawled/Scraped'), ('ai', 'AI Generated')], default='manual', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_key_event', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='sports.match')),
                ('score_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentary', to='sports.scoreevent')),
            ],
            options={
                'verbose_name_plural': 'Live Commentary',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward'), ('batsman', 'Batsman'), ('bowler', 'Bowler'), ('all_rounder', 'All-Rounder'), ('wicket_keeper', 'Wicket Keeper'), ('singles', 'Singles Player'), ('doubles', 'Doubles Player'), ('other', 'Other')], max_length=20)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.URLField(blank=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='sports.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EPGProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('icon', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epg_programs', to='sports.iptvchannel')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['channel', 'start_time', 'end_time'], name='sports_epgp_channel_258481_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('form', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='sports.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_entries', to='sports.team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('league', 'team', 'season')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('team', 'Team'), ('channel', 'IPTV Channel'), ('league', 'League'), ('player', 'Player')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'item_type', 'item_id')},
            },
        ),
    ]
