# Generated by Django 5.0 on 2026-05-13 07:27

import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatchWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_title', models.CharField(default='Live Matches', max_length=100)),
                ('max_matches', models.IntegerField(default=5, help_text='Maximum matches to display')),
                ('show_scores', models.BooleanField(default=True)),
                ('show_time', models.BooleanField(default=True)),
                ('background_color', models.CharField(default='#0B6E4F', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name': 'Live Match Widget',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal ad name', max_length=100)),
                ('ad_url', models.URLField(help_text='Click destination URL')),
                ('ad_text', models.TextField(blank=True, help_text='Advertisement copy')),
                ('placement', models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('inline', 'Inline Content')], default='sidebar', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ad_image', models.ForeignKey(help_text='Advertisement image', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Welcome to Sports Portal', max_length=200)),
                ('hero_subtitle', models.TextField(default='Your ultimate destination for live sports', max_length=500)),
                ('content_sections', wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Main headline', max_length=200)), ('subtitle', wagtail.blocks.TextBlock(help_text='Supporting text', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(help_text='Hero background image')), ('call_to_action_text', wagtail.blocks.CharBlock(max_length=50, required=False)), ('call_to_action_url', wagtail.blocks.URLBlock(required=False))])), ('match_highlights', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section title', max_length=100)), ('featured_matches', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('home_team', wagtail.blocks.CharBlock(max_length=50)), ('away_team', wagtail.blocks.CharBlock(max_length=50)), ('match_time', wagtail.blocks.DateTimeBlock()), ('is_live', wagtail.blocks.BooleanBlock(default=False)), ('score_home', wagtail.blocks.IntegerBlock(required=False)), ('score_away', wagtail.blocks.IntegerBlock(required=False)), ('match_image', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('news_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='News section title', max_length=100)), ('featured_articles', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock(max_length=200)), ('excerpt', wagtail.blocks.TextBlock(max_length=300)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('author', wagtail.blocks.CharBlock(max_length=100)), ('publish_date', wagtail.blocks.DateBlock()), ('article_url', wagtail.blocks.URLBlock(required=False))])))])), ('statistics', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Statistics section title', max_length=100)), ('stats', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(max_length=100)), ('value', wagtail.blocks.CharBlock(max_length=50)), ('icon', wagtail.blocks.CharBlock(help_text='CSS class or emoji', max_length=50))])))])), ('advertisement', wagtail.blocks.StructBlock([('ad_title', wagtail.blocks.CharBlock(help_text='Internal reference name', max_length=100)), ('ad_image', wagtail.images.blocks.ImageChooserBlock(help_text='Advertisement image')), ('ad_url', wagtail.blocks.URLBlock(help_text='Click destination URL')), ('ad_text', wagtail.blocks.TextBlock(help_text='Ad copy text', required=False))]))], blank=True, use_json_field=True)),
                ('hero_background', models.ForeignKey(blank=True, help_text='Hero background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Homepage',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='NewsArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.CharField(help_text='Article author name', max_length=100)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('excerpt', models.TextField(help_text='Brief article summary', max_length=300)),
                ('article_content', wagtail.fields.RichTextField(help_text='Main article content')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('category', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('tennis', 'Tennis'), ('general', 'General Sports')], default='general', max_length=50)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Article featured image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Article',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sports Portal', max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('site_logo', models.ForeignKey(blank=True, help_text='Site logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sport_name', models.CharField(help_text='e.g., Cricket, Football, Tennis', max_length=100)),
                ('sport_icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=10)),
                ('description', wagtail.fields.RichTextField(help_text='Sport description and overview')),
                ('sport_content', wagtail.fields.StreamField([('match_highlights', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section title', max_length=100)), ('featured_matches', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('home_team', wagtail.blocks.CharBlock(max_length=50)), ('away_team', wagtail.blocks.CharBlock(max_length=50)), ('match_time', wagtail.blocks.DateTimeBlock()), ('is_live', wagtail.blocks.BooleanBlock(default=False)), ('score_home', wagtail.blocks.IntegerBlock(required=False)), ('score_away', wagtail.blocks.IntegerBlock(required=False)), ('match_image', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('news_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='News section title', max_length=100)), ('featured_articles', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock(max_length=200)), ('excerpt', wagtail.blocks.TextBlock(max_length=300)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('author', wagtail.blocks.CharBlock(max_length=100)), ('publish_date', wagtail.blocks.DateBlock()), ('article_url', wagtail.blocks.URLBlock(required=False))])))])), ('statistics', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Statistics section title', max_length=100)), ('stats', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(max_length=100)), ('value', wagtail.blocks.CharBlock(max_length=50)), ('icon', wagtail.blocks.CharBlock(help_text='CSS class or emoji', max_length=50))])))])), ('advertisement', wagtail.blocks.StructBlock([('ad_title', wagtail.blocks.CharBlock(help_text='Internal reference name', max_length=100)), ('ad_image', wagtail.images.blocks.ImageChooserBlock(help_text='Advertisement image')), ('ad_url', wagtail.blocks.URLBlock(help_text='Click destination URL')), ('ad_text', wagtail.blocks.TextBlock(help_text='Ad copy text', required=False))]))], blank=True, use_json_field=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Featured sport image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Sport Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
